spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/statistics-service
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
